GTEAMS/urls.py
from django import urls
from django.contrib import admin
from django.urls import path,include
from GTEAMS_APP import views
from django.conf.urls import url, handler404, handler500



urlpatterns = [
    path('admin/', admin.site.urls),
    path('GTEAMS/', include("GTEAMS_APP.urls")),
    path('accounts/',include("accounts.urls")),
    path('accounts/', include('allauth.urls')),
    path('tinymce/',include('tinymce.urls')),

]

GTEAMS_APP/urls.py
from django.conf import urls
from django.urls import path, include
from GTEAMS_APP.models import *
from django.conf import settings
from . import views
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf.urls import url




urlpatterns = [
    # path('', views.PageHome, name='home'),
    
    path('', views.showCoursesMainPage, name='home'),
    path('<str:title>', views.show_detail_MainPage, name='show_detail_MainPage'),
    path('intro/',views.PageIntro,name="intro"),
    path('contact/', views.create_contact, name='contact'),
    path('practice/',views.ShowListQuiz, name='practice'),
    path('courses/', views.showCourses, name='courses'),
    path('courses/yourCart/', views.cartShopping, name="shopping"),
    path('courses/qg/payment/', views.payment, name="payment"),
    path('courses/addCart/', views.addCart, name="buy"),
    path('courses/detailCart/', views.detailCart, name="detailCart"),
    path('blog/', views.blogHome, name='blogs'),
    path('quiz/', views.quizHome, name='quizs'),
    path('login/', views.PageLogin,name='login'),
    path('error/',views.error, name='error'),
    path('searchblog/', views.search_blog, name="searchblog"),
    path('searchquiz/', views.search_quiz, name="searchquiz"),
    path('register/', views.PageRegister,name='register'),
    path('profile/',views.PageProfilee, name='profile'),
    path('courses/<title>/', views.seeCourse, name='seeCourse'),
    path('courses/subject/<subject>/', views.showcourses_detail_demo, name='coursesVideo'),
    path('<str:title>/', views.show_detail_course, name='123'),
    path('courses/cart/delete/<id>/', views.delItem, name="del"),
    path('blog/<str:slug>', views.blogPost, name='blogspost'),
    path('quiz/<str:slug>', views.quizPost, name='quizspost'),
    path('practice/<topic>/',views.ShowQuiz, name='practiceID'),
    path('practice/<topic>/data/',views.ShowQuizID, name='QuizID'),
    path('practice/<topic>/save/',views.save_quiz_view, name='QuizSave'),
    path('courses/<subject>/<title>/', views.showcourses_detail_demo),
    path('blog/postComment/<str:slug>', views.postComment,name="postComment"),
    path('blog/submitBlog/', views.submitBlog,name="submitBlog"),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GTEAMS_APP/models.py
import django
from django.db import models
from django.db.models.base import Model
from django.contrib.auth.models import User
from django.utils.timezone import now
# Contact ----------------------------------------------------------------------------------
class Contact(models.Model):
 
    name = models.CharField(max_length=200)

    email=models.EmailField(max_length=200)
    title=models.CharField(max_length=200)
    content=models.CharField(max_length=1000)
    def __str__(self):
        return self.title
# Practice ---------------------------------------------------------------------------------

class Quiz(models.Model):
    name=models.CharField(max_length=50)
    topic=models.CharField(max_length=200)
    numberOfQuestions=models.IntegerField()
    time=models.IntegerField(help_text="thời gian làm bài tính bằng phút")
    requiredScoreToPass=models.IntegerField(help_text="điểm số cần để hoàn thành bài kiểm tra")
    Ds=models.CharField(max_length=200)
    def __str__(self):
        return f"{self.name}-{self.topic}"
    def get_questions(seft):
        return seft.question_set.all()
    class Meta:
        verbose_name_plural='Quizes'
    
class Question(models.Model):   
    quiz=models.ForeignKey(Quiz,on_delete=models.CASCADE,)
    text=models.CharField(max_length=200)
    created=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return str(self.text)
    def get_answers(seft):
        return seft.answer_set.all()
class Answer(models.Model):
    text=models.CharField(max_length=200)
    correct=models.BooleanField(default=False)
    question=models.ForeignKey(Question,on_delete=models.CASCADE)
    created=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"question: {self.question}, answer:{self.text},correct:{self.correct}"
class Result(models.Model):
    quiz=models.ForeignKey(Quiz, on_delete=models.CASCADE)  
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    score=models.FloatField()
    def __str__(self):
        return str(self.pk)
# Courses ---------------------------------------------------------------------------------

class typeCourse(models.Model):
    Type=models.CharField(max_length=10)
    def __str__(self):
        return self.Type

class subjects(models.Model):
    subjectName = models.CharField(max_length=100)
    def __str__(self):
        return self.subjectName 

from embed_video.fields import EmbedVideoField

class Courses(models.Model):
    title=models.CharField(max_length=100)
    date = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=50)
    linkVideo = EmbedVideoField()
    added = models.DateTimeField(auto_now_add=True)
    MieuTa=models.TextField()
    # subject = models.CharField(max_length=100)
    subject = models.ForeignKey(subjects, on_delete=models.CASCADE)
    Type=models.ForeignKey(typeCourse, on_delete=models.CASCADE)
    costReal = models.CharField(max_length=20, null=True, blank=True)
    image = models.ImageField(upload_to='images/', blank=True, null=True)
    def __str__(self):
        return self.title
    def get_cart(seft):
        return seft.cart_set.all()
    class Meta:
        ordering = ['-added'] 
    
class article_quiz(models.Model):
    sno=models.AutoField(primary_key=True)
    title=models.CharField(max_length=255)
    author=models.CharField(max_length=14)
    slug=models.CharField(max_length=130)
    timeStamp=models.DateTimeField(blank=True)
    content=models.TextField()

    def __str__(self):
        return self.title + " by " + self.author

class article_blog(models.Model):
    sno=models.AutoField(primary_key=True)
    title=models.CharField(max_length=255)
    author=models.CharField(max_length=14)
    slug=models.CharField(max_length=130)
    timeStamp=models.DateTimeField(default=now, blank=True, null=True)
    content=models.TextField()
    views= models.IntegerField(default=0)

    def __str__(self):
        return self.title + " by " + self.author

class BlogComment(models.Model):
    sno= models.AutoField(primary_key=True)
    comment=models.TextField()
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    post=models.ForeignKey(article_blog, on_delete=models.CASCADE)
    parent=models.ForeignKey('self',on_delete=models.CASCADE, null=True, blank=True )
    timestamp= models.DateTimeField(default=now)
    def __str__(self):
        return self.comment[0:13] + "..." + "by" + " " + self.user.username


# cart ---------------------------------------------------------------------------------
class Cart(models.Model):
    title=models.ForeignKey(Courses, on_delete=models.CASCADE)        
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    num=models.IntegerField(default=1)
    paid=models.BooleanField(default=False)
    def __str__(self):
        return str(self.title) 

GTEAMS_APP/views.py
from django.core import paginator
from django.db.models.query import QuerySet
from django.http.response import Http404, HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect, render
import datetime
from django.http import HttpResponse, JsonResponse
from django.views.generic import ListView
import GTEAMS_APP
from GTEAMS_APP.models import *
from GTEAMS_APP.form import *
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from GTEAMS_APP.templatetags import extras
from django.core.paginator import Paginator
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.sites.shortcuts import get_current_site  
from django.db.models import Q
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.csrf import csrf_protect
@login_required(login_url='../../accounts/login')
def PageContact(request):
    return render(request,'pages/contact.html')
    
def PagePractice(request):
    return render(request,'pages/practice.html')
def PageBlogs(request):
    return render(request,'pages/blogs.html')
def PageIntro(request):
    return render(request,'pages/intro.html')


def PageLogin(request):
    return render(request,'pages/login.html')
def PageRegister(request):
    return render(request,'pages/register.html')
def PageCourses(request):
    return render(request,'pages/courses.html')
def PageProfilee(request):
    user=request.user
    context= {'user':user}
    return render(request,'pages/Profile.html',context)

# HOME
def showCoursesMainPage(request):
    allCourses=Courses.objects.all()
    latest_post = Courses.objects.order_by('-date')[:4]
    return render(request,'pages/HomePage.html',{'allCourses': allCourses})

def show_detail_MainPage(request,title):
    try:
        Content=Courses.objects.filter(title=title)
    except Courses.DoesNotExist:
        raise Http404("Practice doesnot exist")
    a=Courses.objects.all()
    context= {'title':title,'question':Content,'a':a}
    return render(request,'pages/coursesVideo.html',context)
#-------------------------------------------------------------------------
# CONTACT

def create_contact(request):
    if request.method == 'GET':
        form=CreateNewContact()
    if request.method == 'POST':
        form=CreateNewContact(request.POST)
        if form.is_valid():
            form.save()
    return render(request,'pages/contact.html',{'form':form})
#--------------------------------------------------------------------------
# PRACTICE

def ShowListQuiz(request):
    Question=Quiz.objects.all()
    context = {'question': Question}
    return render(request,'pages/practice.html',context)
def ShowQuiz(request,topic):
    Question=Quiz.objects.get(topic=topic)
    context = {'question': Question}
    return render(request,'pages/practiceQuiz.html',context)
def ShowQuizID(request,topic):
    quiz=Quiz.objects.get(topic=topic)
    questions=[]
    for q in quiz.get_questions():
        answers=[]
        for a in q.get_answers():
            answers.append(a.text)
        questions.append({str(q): answers})
    return JsonResponse({
        'data':questions,
        'time':quiz.time,
    })
def save_quiz_view(request, topic):
    if (request.is_ajax()):
        questions = []
        data = request.POST
        data_ = dict(data.lists())

        data_.pop('csrfmiddlewaretoken')

        for k in data_.keys():
            print('key: ', k)
            question = Question.objects.get(text=k)
            questions.append(question)
        print(questions)

        user = request.user
        quiz = Quiz.objects.get(topic=topic)

        score = 0
        multiplier = 100 / quiz.numberOfQuestions
        results = []
        correct_answer = None

        for q in questions:
            a_selected = request.POST.get(q.text)
            if a_selected != "":
                question_answers = Answer.objects.filter(question=q)
                for a in question_answers:
                    if a_selected == a.text:
                        if a.correct:
                            score += 1
                            correct_answer = a.text
                    else:
                        if a.correct:
                            correct_answer = a.text

                results.append({str(q): {'correct_answer': correct_answer, 'answered': a_selected}})
            else:
                results.append({str(q): 'not answered'})
            
        score_ = score * multiplier
        Result.objects.create(quiz=quiz, user=user, score=score_)

        if score_ >= quiz.requiredScoreToPass:
            return JsonResponse({'passed': True, 'score': score_, 'results': results})
        else:
            return JsonResponse({'passed': False, 'score': score_, 'results': results})

 
#---------------------------------------------------------------------------------------------------------------
def error(request, exception):
    return render(request,'pages/error.html')

   #ham dua qua html
# COURSES
def showCourses(request):
    allCourses=Courses.objects.all().order_by("-date")
    allSubjects=subjects.objects.all()
    page = request.GET.get('page',1)
    paginator = Paginator(allSubjects,4)
    try:
        pages = paginator.page(page)
    except PageNotAnInteger:
        pages=paginator.page(1)
    except EmptyPage:
        pages=paginator.page(paginator.num_pages)
    context = {'allCourses':allCourses, 'allSubjects':allSubjects,'pages':pages}
    return render(request,'pages/courses.html',context)

# hiện thị video cho user
def show_detail_course(request,title):
    a=Courses.objects.all()
    allSubjects=subjects.objects.all()
    context= {'title':title,'a':a, 'allSubjects':allSubjects}
    return render(request,'pages/coursesVideo.html',context)
    

# trang hiện thi video cho từng khóa học
def showcourses_detail_demo(request,subject):
    allCourses=Courses.objects.all().order_by("-date")
    allSubjects=subjects.objects.all()
    context= {'subject':subject,'allCourses':allCourses, 'allSubjects':allSubjects}
    return render(request,'pages/basecourses.html',context)
#trang mua 
def seeCourse(request,title):
    #user=request.user
    #cart=Cart.objects.filter(user=user)
    cart=Cart.objects.all()
    a=Courses.objects.all()
    allSubjects=subjects.objects.all()
    context= {'title':title,'a':a, 'allSubjects':allSubjects,'cart':cart}
    return render(request,'pages/seeCourse.html',context)

cart ={}
def addCart(request):
    if request.is_ajax():
        id=request.POST.get('id')
        num=request.POST.get('num')
        coDetail = Courses.objects.get(id=id)
        user=request.user
        if id in cart.keys():
            itemCart={
                'name':coDetail.title,
                'price':int(coDetail.costReal),
                'image':str(coDetail.image),
                'num': int(cart[id]['num']) +1,
            }
        else:
            itemCart={
                'name':coDetail.title,
                'price':int(coDetail.costReal),
                'image':str(coDetail.image), 
                'num': num,
            }
        cart[id]=itemCart
        request.session['cart']=cart
        cartInfo=request.session['cart']
        context= {'cart':cartInfo}
        Cart.objects.create(title=coDetail, user=user, paid=False)
        
        return render(request,'pages/addCart.html', context)
    else:
        return render(request,'pages/addCart.html')

def cartShopping(request):
    user=request.user
    allCourses=Courses.objects.all()
    allUser=User.objects.all()
    cart2=Cart.objects.all()
    context= {'cart':cart2, 'allCourses':allCourses, 'allUser':allUser}
    return render(request,'pages/cart.html',context)

def delItem(request, id):
    allCourses=Courses.objects.all()
    allUser=User.objects.all()
    cart=Cart.objects.filter(id=id).delete()
    context= {'cart':cart, 'allCourses':allCourses, 'allUser':allUser}
    return render(request,'pages/cart.html',context)

def detailCart(request):
    return render(request,'pages/detailCart.html')

def payment(request):
    if request.is_ajax():
        user=request.POST.get('user')
        cart1=Cart.objects.all()
        for c in cart1:
            if (str(c.user)==str(user)):
                c.paid=True
                c.save()
    return render(request,'pages/a.html')
#------------------------------------------------------------------------------
# def home(request):
#     allposts = Post.objects.all()
#     totalposts = Post.objects.all().order_by('-date')[:8]
#     context = {'allposts':allposts, 'totalposts':totalposts}
#     return render(request, 'pages/HomePage.html', context)

def blogHome(request): 
    allPosts= article_blog.objects.all().exclude(slug="")
    page = request.GET.get('page',1)
    paginator = Paginator(allPosts,3)
    try:
        pages = paginator.page(page)
    except PageNotAnInteger:
        pages=paginator.page(1)
    except EmptyPage:
        pages=paginator.page(paginator.num_pages)
    context={'allPosts': allPosts, 'pages': pages}
    return render(request, 'pages/blogHome.html',  context)

def blogPost(request, slug): 
    post=article_blog.objects.filter(slug=slug).first()
    post.views= post.views +1
    post.save()
    comments= BlogComment.objects.filter(post=post, parent=None)
    replies= BlogComment.objects.filter(post=post).exclude(parent=None)
    replyDict={}
    for reply in replies:
        if reply.parent.sno not in replyDict.keys():
            replyDict[reply.parent.sno]=[reply]
        else:
            replyDict[reply.parent.sno].append(reply)
    context={'post':post, 'comments': comments, 'user': request.user, 'replyDict': replyDict}
    return render(request, "pages/blogPost.html", context)

def quizHome(request): 
    allPosts= article_quiz.objects.all()
    page = request.GET.get('page',1)

GTEAMS_APP/templates/pages/a.html
hello

GTEAMS_APP/templates/pages/courses.html
{% load static %} {% load embed_video_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>Courses</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="{% static 'fonts/fontawesome-free-5.15.4-web/css/all.css'%}">
    <link rel="stylesheet" href="{% static 'css/cours.css'%}">
</head>
<body>
    <header>
      <div class="container">
        <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #121212;">
        <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'imgs/logo.png'%}" alt="Logo page" width="100" /></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav" style="background-color: #121212">
            <!-- Links -->
        <ul class="navbar-nav mr-auto w-100 justify-content-end">
            <!-- Dropdown -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                  C/C++
                </a>
                <div class="dropdown-menu" >
                    <a class="dropdown-item" href="{% url 'coursesVideo' 'C, C++ cơ bản' %}">C/C++ cơ bản</a>
                    <a class="dropdown-item" href="{% url 'coursesVideo' 'C, C++ nâng cao' %}">C/C++ nâng cao</a>
                </div>
            </li>

            <!-- Dropdown -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                  Python
                </a> {% for i in allCourses %}

                <div class="dropdown-menu">

                    <a class="dropdown-item" href="{% url 'coursesVideo' 'Python cơ bản' %}">Python cơ bản</a>
                    <a class="dropdown-item" href="{% url 'coursesVideo' 'Python nâng cao' %}">Python nâng cao</a>
                    <a class="dropdown-item" href="{% url 'coursesVideo' 'Python luyện tập' %}">Bài tập luyện tập</a>
                </div>
                {% endfor %}
            </li>

            <!-- Dropdown -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                  C#
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'coursesVideo' 'C# Cơ bản' %}">C# Cơ bản</a>
                    <a class="dropdown-item" href="{% url 'coursesVideo' 'C# Winform' %}">C# Winform</a>
                    <a class="dropdown-item" href="{% url 'coursesVideo' 'Lập trình ASP.NET MVC' %}">Lập trình ASP.NET MVC</a>
                </div>
            </li>

            <!-- Dropdown -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                  CSS và SASS
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'coursesVideo' 'CSS và SASS cơ bản' %}">CSS và SASS cơ bản</a>
                    <a class="dropdown-item" href="{% url 'coursesVideo' 'CSS và SASS nâng cao' %}">CSS và SASS nâng cao</a>
                </div>
            </li>
            <!-- Dropdown -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                  Java
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'coursesVideo' 'Java căn bản' %}">Java căn bản</a>
                    <a class="dropdown-item" href="{% url 'coursesVideo' 'Khóa học lập trình Android Cơ bản' %}">Khóa học lập trình Android Cơ bản</a>
                    
                </div>
            </li>
          
          {% if user.is_authenticated %}
          
          <li class="nav-item active"  >
            <a class="nav-link" style="color: #FFD700 !important;" href="{% url 'profile' %}">Xin chào {{ user.username }}</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'shopping'%}"><i class="fas fa-shopping-cart" style="color: #FFD700 !important;"></i></a>
          </li>
        <li class="nav-item active" >
            <a class="nav-link" style="color: #FFD700 !important;" href="{% url 'logout' %}">Đăng xuất</a>
        </li>
        {% else %}
        <li class="nav-item active" >
            <a class="nav-link" style="color: #FFD700 !important;" href="{% url 'log' %}">Đăng nhập</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" style="color: #FFD700 !important;" href="{% url 'reg' %}">Đăng ký</a>
        </li>
          {% endif %}
        </ul>
            
        </div>
    </nav>
      </div>
    </header>
    
    <div class="container">
        <div id="posts">
          <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img src="{% static 'imgs/4.png'%}" alt="1" style=" width: 70%; margin: auto;">
                </div>

                <div class="item">
                    <img src="{% static 'imgs/5.png'%}" alt="2" style="width: 70%; margin: auto;">
                </div>
                <div class="item">
                    <img src="{% static 'imgs/6.png'%}" alt="3" style=" width: 70%; margin: auto;">
                </div>
                <div class="item">
                  <img src="{% static 'imgs/7.png'%}" alt="3" style=" width: 70%; margin: auto;">
              </div>
            </div>

            <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
                <span class="sr-only">Nextttt</span>
            </a>
    </div>
            <div id="posts1">
     
            {% for subject in pages %}
            <h2 style="color: #FFD700; font-size: 15px;">{{subject.subjectName}}</h2>

                <div class="portfolio-item row">
                    {% for course in subject.courses_set.all %}
                    
                    {% if forloop.counter <= 8 %}
                    <div class="item col-lg-3 col-md-4 mt-4">
                        <a href="{% url 'seeCourse' course.title%}" style="color: white;">
                            <div class="main-hover-div">
                                <div class="user-profile-2" style=" width: 255px; margin: 15px;" >
                                    <img src="../media/{{course.image}}" alt="demo" style="width:255px; height:130px;">
                            
                                    <div class="user-data">
                                        <h3 class="titleCourses">{{course.title}}</h3>
                                    </div>
                                    <div>
                                        <i class="fa fa-star" aria-hidden="true" style="color: yellow;"></i>
                                        <i class="fa fa-star" aria-hidden="true" style="color: yellow;"></i>
                                        <i class="fa fa-star" aria-hidden="true" style="color: yellow;"></i>
                                        <i class="fa fa-star" aria-hidden="true" style="color: yellow;"></i>
                                        <i class="fa fa-star" aria-hidden="true" style="color: yellow;"></i>
                                        <span>4.4 (5500)</span>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                   {% endif %}
                    {% endfor %}
                   
                </div>
                {% endfor %}
               {% if pages.has_other_pages %}
                  <ul class="pagination" >
                    {% if pages.has_previous %}
                    <li><a href="?page={{ employees.previous_page_number }}" >«</a></li>
                    {% else %}
                    <li class="disabled" class="page-link" ><span>«</span></li>
                    {% endif %}

                    {% for i in pages.paginator.page_range %}

                       {% if pages.number == i %}
                       <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                       {% else %}
                       <li><a href="?page={{ i }}">{{ i }}</a></li>
                       {% endif %}
                       {% endfor %}

                       {% if pages.has_next %}
                       <li><a href="?page={{ pages.next_page_number }}">»</a></li>
                       {% else %}
                       <li class="disabled"><span>»</span></li>
                       {% endif %}
                  </ul>
                {% endif %} 
            </div>
        </div>
    </div>

    <footer>
        <div class="container">
          <div class="text-center"><i class="fas fa-ellipsis-h"></i></div>
          
          <div class="row text-center">
            <div class="col-md-4 box">
              <span class="copyright quick-links">GTEAMS &copy; Our Website <script>document.write(new Date().getFullYear())</script>
              </span>
            </div>
            <div class="col-md-4 box">
              <ul class="list-inline social-buttons">
                <li class="list-inline-item">
                  <a href="#">
                  <i class="fab fa-twitter"></i>
                </a>
                </li>
                <li class="list-inline-item">
                  <a href="#">
                  <i class="fab fa-facebook-f"></i>
                </a>
                </li>
                <li class="list-inline-item">
                  <a href="#">
                  <i class="fab fa-linkedin-in"></i>
                </a>
                </li>
              </ul>
            </div>
            <div class="col-md-4 box">
              <ul class="list-inline quick-links">
                <li class="list-inline-item">
                  <a href="#">Privacy Policy</a>
                </li>
                <li class="list-inline-item">
                  <a href="#">Terms of Use</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </footer>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" integrity="sha384-1CmrxMRARb6aLqgBO7yyAxTOQE2AKb9GfXnEo760AUcUmFx3ibVJJAzGytlQcNXd" crossorigin="anonymous"></script>
      <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    </body>
</html>